In [2]:
import matplotlib.pyplot as plt
from matplotlib import rc
import numpy as np
from scipy.optimize import curve_fit
from uncertainties import ufloat
from uncertainties import unumpy as unp
import array_to_latex as a2l
import csv
import pandas as pd
from astropy.io.votable import parse
from astropy.table import QTable, Table, Column

rc('font', **{'family': 'serif', 'serif': ['Computer Modern']}) #font na grafih je LaTexov
rc('text', usetex=True)

In [18]:
mi_0 = 4e-7 * np.pi
N = unp.uarray([60], [0])
l = unp.uarray([60], [0.5]) * 1e-2
d = unp.uarray([12.7e-2], [0.6e-2])

data = np.loadtxt('meritev1.txt')

I = unp.uarray(data[:, 1], [0.1] * 4) * 1e-3

B = mi_0 * N * I / (unp.sqrt(l ** 2 + d ** 2))


np.average(unp.nominal_values(B)) * 1e6, np.average(unp.std_devs(B)) * 1e6, np.average(unp.std_devs(B)) / np.average(unp.nominal_values(B))

(21.91402956615779, 0.18076592617286003, 0.008248867495005115)

In [16]:
print(a2l.to_ltx(data, frmt='{:6.2f}', arraytype='array'))

\begin{array}
   20.00 &  205.20\\
   15.00 &  193.60\\
   10.00 &  180.00\\
    5.00 &  134.20
\end{array}
None


In [19]:
m_m = unp.uarray([44e-3], [0.5e-3])
r = unp.uarray([16e-3/2], [0.5e-3/2])
l = unp.uarray([45e-3], [0.5e-3])

# Plastic hollow cylinder case.
m_t = unp.uarray([6e-3], [0.5e-3])
r_1 = unp.uarray([17e-3/2], [0.5e-3/2])
r_2 = unp.uarray([19e-3/2], [0.5e-3/2])
L = unp.uarray([50e-3], [0.5e-3])

In [43]:
t = unp.uarray(np.average(1/10 * np.array([23.97, 23.68, 23.96])), np.std(1/10 * np.array([23.97, 23.68, 23.96])))

t

array(2.387+/-0.013441230102437385, dtype=object)

In [44]:
J_m = m_m/12 * (3*r**2 + l**2)

J_t = m_t/12 * (3*(r_1**2 + r_2**2) + L**2)

J = J_m + J_t

J_m *1e6, J_t * 1e6, J * 1e6 

(array([8.129+/-0.1941497891448765], dtype=object),
 array([1.4937500000000004+/-0.12732426785192122], dtype=object),
 array([9.62275+/-0.23217581658955735], dtype=object))

In [45]:
prod = J * (2 * np.pi / t)**2

prod

array([6.667363015284236e-05+/-1.7753024974907466e-06], dtype=object)

In [39]:
data = np.loadtxt('meritev2.txt')

data[:, 0] = data[:, 0] + 9.5 + 2.25

print(a2l.to_ltx(data, frmt='{:6.2f}', arraytype='array'))

x = unp.uarray(data[:, 0], [0.5] * 7) * 1e-2

kot = unp.uarray(np.deg2rad(data[:, 1]), np.deg2rad([2] * 7))

kot

\begin{array}
   23.75 &   60.00\\
   26.75 &   49.00\\
   31.75 &   33.00\\
   36.75 &   22.00\\
   41.75 &   15.00\\
   46.75 &   10.00\\
   51.75 &    7.00
\end{array}
None


array([1.0471975511965976+/-0.03490658503988659,
       0.8552113334772214+/-0.03490658503988659,
       0.5759586531581288+/-0.03490658503988659,
       0.3839724354387525+/-0.03490658503988659,
       0.2617993877991494+/-0.03490658503988659,
       0.17453292519943295+/-0.03490658503988659,
       0.12217304763960307+/-0.03490658503988659], dtype=object)

In [41]:
ratios = unp.tan(kot) * 4 * np.pi / mi_0 * (x)**3

R = unp.uarray(np.average(unp.nominal_values(ratios)), np.average(unp.std_devs(ratios)))

R

array(200847.56181263528+/-28388.07687960279, dtype=object)

In [42]:
B_Z = unp.sqrt(prod/R)

B_Z * 1e6

array([18.21980685671898+/-1.3102555089184256], dtype=object)